### ISSUE TITLE
Feature request: possibility to set test filter in configuration

### ISSUE THREAD

**Issue by ebabenskas** [hjanuschka/fastlane-plugin-aws_device_farm#13]
Is it possible to set filter of test in configuration file? I didn't find anything like this. 
I'm talking about this feature, which i can do over AWS console. 
This test filter field in screenshots: [Link]( http://imgur.com/a/cMPXF)
I saw  that AWS API support this field.

**Comment by hjanuschka** [comment]
@ebabenskas #16 got merged, where @Rackles  added the feature, many THX!! gem has been pushed as `v0.3.4`
