### ISSUE TITLE
Release 0.3.11 crashes

### ISSUE THREAD

**Issue by dermaaarkus** [hjanuschka/fastlane-plugin-aws_device_farm#26]
My iOS fastlane pipelines are crashing, because of your changes in Release 0.3.11 including PR #25 . 

> "‌Could not find option 'is_unit_test' in the list of available options: name, run_name, binary_path, test_binary_path, test_package_type, test_type, path, device_pool, wait_for_completion, allow_device_errors, allow_failed_tests, filter, billing_method, locale, test_spec, print_web_url_of_run‌ "

Could you please revert the change or bring an update soon, that fixed it?

@hjanuschka @tedgonzalez

**Comment by tedgonzalez** [comment]
Hi sorry about that. Please use this at the moment in your pluginfile

> gem 'aws_device_farm', 'v0.3.10'

**Comment by tedgonzalez** [comment]
Sorry about that, please specify this in your pluginfile while we are fixing it

> gem 'fastlane-plugin-aws_device_farm', '~>0.3.10'

**Comment by hjanuschka** [comment]
thx @tedgonzalez - ` v0.3.12` with the fix from #27  released just now!

**Comment by dermaaarkus** [comment]
Thank you guys for your fast fix!
