### ISSUE TITLE
Support for unmetered device slots

### ISSUE THREAD

**Issue by tspecht** [hjanuschka/fastlane-plugin-aws_device_farm#28]
Hey,

Does this plugin have built-in support for using unmetered device slots when creating a test run instead of using metered billing?

**Comment by cmarchal** [comment]
Hey @tspecht ,
It's already implemented but not documented. You can use it like:

`    aws_device_farm(
      name: "XXX",
      ...
      billing_method: "UNMETERED"
    )
`

**Comment by hjanuschka** [comment]
closing this, someone willing to do a PR for README update?
