### ISSUE TITLE
Problems to download the last fixed version

### ISSUE THREAD

**Issue by t0nimas** [hjanuschka/fastlane-plugin-aws_device_farm#32]
I use this repo isolated and its working. But when I am trying to add to other fastlane project:
`fastlane add_plugin aws_device_farm` 
the version is still before fixing: "Do not let descriptions end with a '.'"
I tried to update fastlane and bundler but is still the same version: fastlane-plugin-aws_device_farm 0.3.13
Could you help me how to solve this?
I am new on this but I think that I need that you build a new release to be available in rubygems.org right?
Thank you.

**Comment by hjanuschka** [comment]
should be released now in 0.3.15
