### ISSUE TITLE
v0.3.19 Usage Error

### ISSUE THREAD

**Issue by coreypett** [hjanuschka/fastlane-plugin-aws_device_farm#45]
I recently updated the plugin to version 0.3.19 have been receiving the following error:

`Unknown method 'params'`
`Error loading plugin 'fastlane-plugin-aws_device_farm': To call another action from an action use other_action.params instead`

I am putting this on your radar to see if you have any immediate ideas. Otherwise, I should have some time this week to dig into this.

Appreciate it, 
Thanks

**Comment by hjanuschka** [comment]
sry for that, should be fixed with:`0.3.21`  can you verify?

**Comment by coreypett** [comment]
Works for me, thank you
