### ISSUE TITLE
'Project Fastlane not Found' error 

### ISSUE THREAD

**Issue by lukasburns1** [hjanuschka/fastlane-plugin-aws_device_farm#6]
Hi , im getting the following error when running the plugin for ios  'Project Fastlane not Found'
my lane looks like this :  
lane :ios_aws_device_farm do
  ENV['AWS_ACCESS_KEY_ID']     = 'XXXXXXXXXX'
  ENV['AWS_SECRET_ACCESS_KEY'] = 'XXXXXXXXX
  ENV['AWS_REGION']            = 'us-west-2'

  #Build For Testing
  xcodebuild(
    scheme: 'FoodPin',
    destination: 'generic/platform=iOS',
    configuration: 'Release',
    derivedDataPath: 'aws',
    xcargs: "GCC_PREPROCESSOR_DEFINITIONS='AWS_UI_TEST' ENABLE_BITCODE=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO build-for-testing"
  )
  # Transform .app into AWS compatible IPA
  aws_device_farm_package(
    derrived_data_path: "aws",
    configuration: "Release"
  )
  # RUN tests on AWS Device Farm
  aws_device_farm
 end

I've been trying to fix it by exporting some paths, re installing fastlane etc but cant make it work.
was wondering if anyone had a similar issue and how they fixed it.

thanks!

**Comment by hjanuschka** [comment]
@lukasburns1 this is maybe misleading by the default value, you first of all have to create a project in "Mobile Device Farm"  on AWS - this project has a name, and that should be "fastlane" - if not you have to set the name value. 


e.g.:

```ruby
aws_device_farm_package(
derrived_data_path: "aws",
configuration: "Release",
name: "my-custom-project-name"
)
```

**Comment by lukasburns1** [comment]
Hi thanks for the quick response, much appreciated, it works perfectly if I put the name parameter on the aws_device_farm options!

cheers!

**Comment by hjanuschka** [comment]
@lukasburns1 good to hear, pushed a release yesterday, which should make the error message a bit more clear.
